apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: techtrends-staging
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  source:
    repoURL: 'https://github.com/vuongdq084/udacity-nd064-course-1'
    targetRevision: HEAD
    path: project/helm
    helm:
      valueFiles:
        - values-staging.yaml
  project: default
  syncPolicy: {}