name: TechTrends - Package with Docker

## Trigger on every push to the main branch
on:
  push:
    branches:
      - main
jobs:  
  build:
    ## Run the action on the ubuntu-latest operating system
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./project
          file: ./project/Dockerfile
          platforms: linux/amd64
          push: true
          tags: vuongdq2503/techtrends:latest